# Pandas

In [19]:
import pandas as pd

Get the csv data from the file, we either use \\ or / for the file path

In [14]:
# csv_dataframe = pd.read_csv('C:\\Users\\fbhug\\OneDrive\\Desktop\\ML Finance\\data1.csv')

In [20]:
csv_dataframe = pd.read_csv('C:/Users/fbhug/OneDrive/Desktop/ML Finance/data1.csv')

In [23]:
csv_dataframe.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30

In [21]:
csv_dataframe.tail(5) # last 5 items

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
95,AMT,AMERICAN TOWER C,Real Estate,0.46,64886514,147.19,160.68
96,ISRG,INTUITIVE SURGIC,Health Care,1.32,64649581,568.36,556.59
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68

In [22]:
csv_dataframe.shape

(100, 7)

To find the maximum and minimum

In [24]:
print(csv_dataframe.min())
print('--------')
print(csv_dataframe.max())

Ticker               AAPL
Name                 3MCO
Beta                 0.22
Market Cap       63890227
Current Price       12.68
Price Target        15.56
dtype: object
--------
Ticker                        XOM
Name             WELLS FARGO & CO
Beta                         1.84
Market Cap             1081130615
Current Price              324999
Price Target               357125
dtype: object

In [25]:
csv_dataframe.describe()

             Beta    Market Cap  Current Price   Price Target
count  100.000000  1.000000e+02     100.000000      93.000000
mean     0.995800  1.756136e+08    3441.165500    4051.011720
std      0.283446  1.806083e+08   32481.881894   37011.566893
min      0.220000  6.389023e+07      12.680000      15.560000
25%      0.810000  8.195384e+07      69.630000      74.530000
50%      0.990000  1.119556e+08     117.600000     123.930000
75%      1.182500  1.987309e+08     219.430000     217.130000
max      1.840000  1.081131e+09  324999.000000  357125.000000

In [26]:
csv_dataframe['Beta']

0     1.09
1     1.23
2     1.46
3     1.44
4     1.13
      ...
95    0.46
96    1.32
97    0.96
98    0.74
99    1.01
Name: Beta, Length: 100, dtype: float64

To find the unique sector of a series (sector)

In [27]:
print(csv_dataframe.Sector.unique())

['Information Technology' 'Consumer Discretionary' 'Financials'
 'Health Care' 'Energy' 'Consumer Staples' nan
 'Telecommunication Services' 'Industrials' 'Information Technology .'
 'Materials' 'Industrial$' 'Utilities' 'Enersy' 'lndustrials'
 'Real Estate']

In [28]:
print(csv_dataframe.Ticker.unique()) # unique ticker

['AAPL' 'AMZN' 'MSFT' 'GOOGL' 'BRK/A' 'FB' 'JPM' 'JNJ' 'XOM' 'SAC' 'V'
 'WMT' 'SPY' 'WFC' 'UNH' 'PFE' 'T' 'HD' 'MA' 'VZ' 'CVX' 'CSCO' 'INTC' 'PG'
 'BA' 'ORCL' 'KO' 'MRK' 'C' 'CMCSA' 'NVDA' 'IW' 'DIS' 'PEP' 'NFLX' 'DWDP'
 'ABBV' 'IBM' 'ADBE' 'NKE' 'AMGN' 'MCD' 'PM' 'HON' 'MMM' 'ABT' 'CRM' 'MO'
 'UNP' 'LLY' 'QCOM' 'UTX' 'GE' 'PYPL' 'VTI' 'VOO' 'UPS' 'COST' 'TXN' 'BMY'
 'AVGO' 'TMO' 'LMT' 'GILD' 'AXP' 'LOW' 'BKNG' 'GS' 'USB' 'CAT' 'COP' 'SLB'
 'MS' 'FOXA' 'CHTR' 'NEE' 'CVS' 'BLK' 'OHR' 'SBUX' 'KHC' 'QQQ' 'ANTM'
 'EFA' 'VEA' 'WBA' 'BDX' 'SCHW' 'EOG' 'BIIB' 'FDX' 'TJX' 'VMW' 'AET' 'PNC'
 'AMT' 'ISRG' 'ADP' 'MOLZ' 'AGN']

Creating a new Price Increase series (Price Target - Current Price)

In [33]:
csv_dataframe['Price Increase'] = csv_dataframe['Price Target'] - csv_dataframe['Current Price']

In [34]:
csv_dataframe.head(5)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price_diff,Price Increase
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,-8.43,8.43
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,-163.20,163.20
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,-8.93,8.93
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,-206.91,206.91
4,BRK/A,BERKSHIRE HATH-A,Financials,1.13,534247506,324999.00,357125.00,-32126.00,32126.00

In [38]:
csv_dataframe['Return'] = csv_dataframe['Price Increase'] / csv_dataframe['Current Price']

In [ ]:
csv_dataframe.Return.()

In [37]:
csv_dataframe.Return.describe()

count    93.000000
mean      0.093774
std       0.073729
min      -0.046877
25%       0.034946
50%       0.078769
75%       0.148719
max       0.270456
Name: Return, dtype: float64

In [41]:
boolean_mask = csv_dataframe.Return > 0.15

In [42]:
boolean_mask

0     False
1     False
2     False
3      True
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Return, Length: 100, dtype: bool

This __csv_dataframe[boolean_mask]__ will show only stocks with return greater than 0.15

In [44]:
csv_dataframe[boolean_mask]

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price_diff,Price Increase,Return
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,-206.91,206.91,0.175648
5,FB,FACEBOOK INC-A,Information Technology,1.33,468653343,162.32,205.93,-43.61,43.61,0.268667
20,CVX,CHEVRON CORP,Energy,0.93,224917340,117.38,143.86,-26.48,26.48,0.225592
22,INTC,INTEL CORP,Information Technology,1.58,209984946,45.54,56.18,-10.64,10.64,0.233641
28,C,CITIGROUP INC,Financials,1.08,177521345,70.54,83.04,-12.50,12.50,0.177204
29,CMCSA,COMCAST CORP-A,Consumer Discretionary,0.94,169348252,36.96,43.48,-6.52,6.52,0.176407
35,DWDP,DOWDUPONT INC,Materials,1.36,158239900,68.58,81.26,-12.68,12.68,0.184894
42,PM,PHILIP MORRIS IN,Consumer Staples,0.57,123319026,79.33,93.58,-14.25,14.25,0.179629
52,GE,GENERAL ELECTRIC,Industrials,0.81,110202905,12.68,15.56,-2.88,2.88,0.227129
58,TXN,TEXAS INSTRUMENT,Information Technology,1.36,102430474,105.36,123.93,-18.57,18.57,0.176253
60,AVGO,BROADCOM INC,Information Technology,0.99,97714004,236.34,286.03,-49.69,49.69,0.210248
63,GILD,GILEAD SCIENCES,Health Care,1.14,95125471,73.38,88.04,-14.66,14.66,0.199782
66,BKNG,BOOKING HOLDINGS,Consumer Discretionary,0.74,90969219,1916.27,2222.78,-306.51,306.51,0.159951
67,GS,GOLDMAN SACHS GP,Financials,1.20,89898222,229.24,274.83,-45.59,45.59,0.198875
69,CAT,CATERPILLAR INC,Industrials,1.49,86117745,144.90,169.73,-24.83,24.83,0.171360
71,SLB,SCHLUMBERGER LTD,Energy,0.92,84749599,61.23,77.79,-16.56,16.56,0.270456
72,MS,MORGAN STANLEY,Financials,1.37,84081418,48.19,58.57,-10.38,10.38,0.215397
74,CHTR,CHARTER COMMUN-A,Consumer Discretionary,0.78,81973731,318.13,374.75,-56.62,56.62,0.177978
77,BLK,BLACKROCK INC,Financials,1.34,76431688,476.06,587.79,-111.73,111.73,0.234697
80,KHC,KRAFT HEINZ CO/T,Consumer Staples,0.84,71894589,58.97,68.00,-9.03,9.03,0.153129
87,SCHW,SCHWAB (CHARLES),Financials,1.35,69120369,51.16,60.33,-9.17,9.17,0.179242
88,EOG,EOG RESOURCES,Enersy,0.86,68241437,117.82,140.69,-22.87,22.87,0.194110
89,BIIB,BIOGEN INC,Health Care,1.10,68224664,338.68,390.00,-51.32,51.32,0.151529

This ~ operator shows the inverse, that is stock that are < 0.15

In [47]:
csv_dataframe[~boolean_mask]

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price_diff,Price Increase,Return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,-8.43,8.43,0.037661
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,-163.20,163.20,0.082835
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,-8.93,8.93,0.078769
4,BRK/A,BERKSHIRE HATH-A,Financials,1.13,534247506,324999.00,357125.00,-32126.00,32126.00,0.098850
6,JPM,JPMORGAN CHASE,Financials,1.14,381460349,113.50,122.15,-8.65,8.65,0.076211
...,...,...,...,...,...,...,...,...,...,...
95,AMT,AMERICAN TOWER C,Real Estate,0.46,64886514,147.19,160.68,-13.49,13.49,0.091650
96,ISRG,INTUITIVE SURGIC,Health Care,1.32,64649581,568.36,556.59,11.77,-11.77,-0.020709
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,1.73,-1.73,-0.011732
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20,-5.40,5.40,0.123288
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68,-23.46,23.46,0.124641

Dsiplaying only technology company

In [51]:
Info_tech = csv_dataframe[csv_dataframe.Sector == "Information Technology"]
Info_tech

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price_diff,Price Increase,Return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,-8.43,8.43,0.037661
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,-8.93,8.93,0.078769
3,GOOGL,ALPHABET INC-A,Information Technology,1.44,817459888,1177.98,1384.89,-206.91,206.91,0.175648
5,FB,FACEBOOK INC-A,Information Technology,1.33,468653343,162.32,205.93,-43.61,43.61,0.268667
10,V,VISA INC-CLASS A,Information Technology,1.15,300743721,147.84,159.43,-11.59,11.59,0.078396
18,MA,MASTERCARD INC-A,Information Technology,1.18,226341093,217.96,228.18,-10.22,10.22,0.046889
21,CSCO,CISCO SYSTEMS,Information Technology,1.30,216681234,47.40,50.15,-2.75,2.75,0.058017
22,INTC,INTEL CORP,Information Technology,1.58,209984946,45.54,56.18,-10.64,10.64,0.233641
25,ORCL,ORACLE CORP,Information Technology,1.02,196071883,49.25,54.48,-5.23,5.23,0.106193
37,IBM,IBM,Information Technology,0.98,135390904,148.33,165.10,-16.77,16.77,0.113059
38,ADBE,ADOBE SYS INC,Information Technology,1.34,134505431,274.69,288.31,-13.62,13.62,0.049583
46,CRM,SALESFORCE.COM,Information Technology,1.12,119172686,157.49,169.68,-12.19,12.19,0.077402
50,QCOM,QUALCOMM INC,Information Technology,1.28,110315545,75.09,71.57,3.52,-3.52,-0.046877
53,PYPL,PAYPAL HOLDINGS,Information Technology,1.25,107453792,90.78,97.83,-7.05,7.05,0.077660
58,TXN,TEXAS INSTRUMENT,Information Technology,1.36,102430474,105.36,123.93,-18.57,18.57,0.176253
60,AVGO,BROADCOM INC,Information Technology,0.99,97714004,236.34,286.03,-49.69,49.69,0.210248
92,VMW,VMWARE INC-CL A,Information Technology,1.21,66480574,162.65,165.20,-2.55,2.55,0.015678
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73,1.73,-1.73,-0.011732

To find the mean by sector we use **groupby**

In [53]:
csv_dataframe.groupby('Sector').mean()

,Beta,Market Cap,Current Price,Price Target,Price_diff,Price Increase,Return
Sector,,,,,,,
Consumer Discretionary,0.907692,1.875567e+08,422.383846,468.329231,-45.945385,45.945385,0.086719
Consumer Staples,0.675000,1.392211e+08,88.859000,94.648000,-5.789000,5.789000,0.079098
Energy,0.910000,1.865371e+08,83.757500,97.650000,-13.892500,13.892500,0.164425
Enersy,0.860000,6.824144e+07,117.820000,140.690000,-22.870000,22.870000,0.194110
Financials,1.155000,1.856177e+08,27198.074167,29894.575833,-2696.501667,2696.501667,0.137083
Health Care,0.954211,1.275709e+08,177.760000,186.905789,-9.145789,9.145789,0.056757
Industrial$,1.190000,1.219452e+08,207.880000,217.130000,-9.250000,9.250000,0.044497
Industrials,1.032500,1.189380e+08,179.236250,198.453750,-19.217500,19.217500,0.112912
Information Technology,1.224444,2.958042e+08,199.093889,222.621667,-23.527778,23.527778,0.096953
Information Technology .,1.840000,1.680694e+08,276.430000,286.090000,-9.660000,9.660000,0.034946
Materials,1.360000,1.582399e+08,68.580000,81.260000,-12.680000,12.680000,0.184894
Real Estate,0.460000,6.488651e+07,147.190000,160.680000,-13.490000,13.490000,0.091650
Telecommunication Services,0.665000,2.347001e+08,44.075000,46.020000,-1.945000,1.945000,0.048400
Utilities,0.220000,8.189415e+07,173.650000,176.720000,-3.070000,3.070000,0.017679
lndustrials,1.120000,6.754730e+07,255.440000,283.180000,-27.740000,27.740000,0.108597